scan_filter_chain:
- name: angular_low
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: -3.1415 
    upper_angle: -1.7
- name: angular_up
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: 1.7
    upper_angle: 3.1415

